### ISSUE TITLE
"Hotkey" is better default behavior to show usages

### ISSUE THREAD

**Issue by utuhiro78** [fcitx/mozc#11]
"Hotkey" is better default behavior to show usages.
Japanese "Usages" are too wide. Japanese users don't read them.

1. Type "oku" (= put) and press space twice.
![fcitx5-mozc-usages](https://user-images.githubusercontent.com/34818411/102689353-af38af80-4240-11eb-9057-72e016e346fe.png)

**Comment by utuhiro78** [comment]
"Don't show Usage" option is the best for me.
The pop-up window is rather wide for two characters.

![fcitx5-mozc-usage-hotkey](https://user-images.githubusercontent.com/34818411/102689878-ef019600-4244-11eb-8b7c-2e8a4f51cad3.png)

**Comment by wengxt** [comment]
I was suggested that this behavior is similar to ibus mozc (when using its gtk renderer).
