### ISSUE TITLE
Need fixes for composition modes

### ISSUE THREAD

**Issue by utuhiro78** [fcitx/mozc#12]
I tested fcitx5-mozc on the Plasma desktop. Fcitx5-mozc shows composition modes, 
but some of them are unnecessary/broken.

![fcitx5-mozc-2020122701](https://user-images.githubusercontent.com/34818411/103165264-e880a900-4858-11eb-86b5-93606e5b3017.png)

There are six entries.
1. Full width alphabet icon + Half width alphabet: It's unnecessary and doesn't work.
2. Hiragana icon + Hiragana: OK
3. Full width Katakana icon + Full width Katakana: OK
4. Full width alphabet icon + Full width alphabet: OK
5. Half width alphabet icon + Half width alphabet: OK
6. Full width Katakana icon + Half width Katakana: It should be "Half width Katakana icon + Half width Katakana" (ui-katakana_half.png + ｱ). It doesn't work. This mode need to convert "aiueo" to "ｱｲｳｴｵ" (In mode 2, type "aiueo" and press F8).

**Comment by wengxt** [comment]
Yeah, I agree. looks like the direct mode is only useful when it is kana mode instead of romaji.

**Comment by wengxt** [comment]
Also the label is only one character is also kinda because of an old limitation in fcitx 4, which should probably be updated to a more meaningful string.

**Comment by wengxt** [comment]
Direct and half katakana mode should be fixed by now.
