### ISSUE TITLE
Fcitx5-mozc always shows a vertical candidate list

### ISSUE THREAD

**Issue by utuhiro78** [fcitx/mozc#13]
I disabled "vertical candidate list", but fcitx5-mozc always shows a vertical list.

![fcitx5-mozc-2020122702](https://user-images.githubusercontent.com/34818411/103165839-fb4aac00-485f-11eb-8e60-a90d156c9d00.png)

![fcitx5-mozc-2020122703](https://user-images.githubusercontent.com/34818411/103165840-01408d00-4860-11eb-9649-bd3f2662dd1c.png)

**Comment by wengxt** [comment]
this is by design.. because mozc doesn’t really work for horizontal list.

the input method code is allowed force a layout if it wants to.
