### ISSUE TITLE
The latest fcitx5 doesn't show the mozc icon on the Xfce panel

### ISSUE THREAD

**Issue by utuhiro78** [fcitx/mozc#28]
Hello,
The latest fcitx5 doesn't show the mozc icon on the Xfce panel.

![fcitx5-mozc-icon](https://user-images.githubusercontent.com/34818411/162586416-e1328cb6-02f3-4c54-b893-813661b4202e.png)

I'm using fcitx5-5.0.15 and fcitx5-mozc d7f167e on the Xfce desktop (Arch Linux).

See also:
https://twitter.com/ikunya/status/1512708719666434049

**Comment by wengxt** [comment]
your screenshot looks right, is that what you see or is that what you expected to see?

**Comment by wengxt** [comment]
Also, just FYI, there's a change to fcitx5-mozc, that uses input method icon instead of the mozc icon for tray. If that's what you have in the screenshot, it's an expected change.

https://github.com/fcitx/mozc/commit/53e273544bc5dfcff7ee7fd4113443a93269c158

The twitter link is another irrelevant debian bug. I just reported it here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1009254

**Comment by utuhiro78** [comment]
We could see the icon in the previous version.
![org fcitx Fcitx5 fcitx-mozc](https://user-images.githubusercontent.com/34818411/162635116-96e37a35-0d60-4817-abb6-f0f1d2514763.png)
( /usr/share/icons/hicolor/128x128/apps/org.fcitx.Fcitx5.fcitx-mozc.png )

You will find the icon on top-right.
https://storage.googleapis.com/zenn-user-upload/992ied47r40g3b7g4zq42gza1tsu
( https://zenn.dev/ikuya/articles/f42da50d670a8562a12e )

**Comment by utuhiro78** [comment]
Some users may prefer the monochrome icon.
I didn't know if it was a bug, but I decided to post this issue as a reminder after I found Ikunya's tweet.
I prefer the old orange icon because it stands out.

Thank you for the replies. Maybe this is not a bug. :-)

**Comment by wengxt** [comment]
here’s the thing, the icon installed by fcitx is not monochrome

Here’s the icon in our repo, despite it’s not same as the old one, it’s also an orange one.
https://github.com/fcitx/mozc/blob/fcitx/scripts/icons/ui-hiragana.png

I bet the icon you saw is either from your icon theme, or your tray colorize all icon it tries to display.

**Comment by utuhiro78** [comment]
> I bet the icon you saw is either from your icon theme, 

wengxt,
The famous icon theme "Papirus" has added fcitx-mozc icons on 3 Feb !! https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/c5cfe59a8bae5e62cecbbb424fdbc7f0f12d83b2

I removed the fcitx-mozc icons in the Papirus theme,

```
rm -f ~/.local/share/icons/Papirus*/*/*/*mozc*
gtk-update-icon-cache ~/.local/share/icons/Papirus/
gtk-update-icon-cache ~/.local/share/icons/Papirus-Dark/
gtk-update-icon-cache ~/.local/share/icons/Papirus-Light/
```

and I can see your icon now.

![fcitx-mozc-tray-icon](https://user-images.githubusercontent.com/34818411/162643044-296e9928-3c63-4191-97fe-bc6d331a2810.png)

Sorry for the confusion.
