### ISSUE TITLE
Predefined ON/OFF keys for mozc does not work

### ISSUE THREAD

**Issue by oech3** [fcitx/mozc#39]
**Describe the bug**
`xkeyboard-config-2.36` does not define Lang1/Lang2 as HNGL/HJCV.
It caused some keys undetectable by `mozc` (https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/326). `mozc` was changed to use predefined ON/OFF keys (https://github.com/google/mozc/issues/552#issuecomment-1568743184). But they does not work with `fcitx5-5.0.23`.

**To Reproduce**
1. Set XkbModel to `applealu_jis`.
2. Type `Eisu` when `Mozc` is enabled.
Result: `Mozc` is still active(still possible to type Japanese).

**Expected behavior**
`Mozc` should be inactive(unable to type Japanese).

**Desktop**
 - Desktop: `MATE 1.25.1`
 - Display server type: `X11`

**Comment by wengxt** [comment]
While the fix is submitted, you might also want to check fcitx5's global option since hangul and hangul_hanja are also used by the global option.
