### ISSUE TITLE
Prolonged Sound Mark "ー" tobe "ろ" in kana input.

### ISSUE THREAD

**Issue by reasonset** [fcitx/mozc#40]
**Description**
When using the Japanese keyboard and using Kana input, pressing the "¥|" key in the upper right corner should input a prolonged sound mark "ー", but "ろ" will be input.

**Steps to reproduce**

1. Use Japanese Keyboard
2. Use Kana input
3. put "¥|" key

**Expected behavior**
Input "ー".

**Actual behavior**
Input "ろ".

**Version or commit-id**
Mozc-2.29.5111.102+24.11.oss

**Environment**
- OS: Manjaro
- IMF (for Linux): Fcitx5
- Related Applications none

**Investigations**
 - Whether this issue happens on both Ibus and other IMF (e.g. Fcitx, uim).
   + N/A
 - Whether this issue happens on other IMEs (e.g. Anthy, SKK).
   + Some IME has same problem. But generally no (kkc 5.0.12 don't have it).
 - What applications this issue happens on (e.g. Chromium, gedit).
   + Firefox, Vivaldi, Chromium, Xed, Leafpad, L3afpad, Falkon
 - What applications this issue does not happen on (e.g. Chromium, gedit).
   + Not-found
 - (optional) What versions or commit-ids this issue did not happen on
   (e.g. Mozc-2.28.4960.100+24.11.oss).
   + Mozc(HEAD on Jun 14 fcitx branch), Abseil(1feab4f), Breakpad(8988364), Googletest(65cfeca), gyp(c6d8b9f), JSONCPP(3d9bf8e), Protobuf(3560e23), Bazel(2.29.5111.102)

**Additional context**

Only when press with shift key, "ー" is entered.

Maybe this problem is caused by  `aa69eae` commit. It deletes key bindings that

```diff
-    // A backslash is handled in a special way because it is input by
-    // two different keys (the one next to Backslash and the one next
-    // to Right Shift).
-    {'\\', {"ろ", "ろ"}},
-    {U'¥', {"ー", "ー"}},  // U+00A5
```

I have confirmed that this problem does not occur when building with commit `99cd187`.

This issue was directed from [Google Mozc](https://github.com/google/mozc/issues/759).

**Comment by wengxt** [comment]
Thanks for the report.

There's a bug introduced in  aa69eae when merging the ibus's key translator code because ibus's key code is different comparing to fcitx's key code. Should be fixed by https://github.com/fcitx/mozc/commit/a0fc18bc99efd02cb2f5c854ac9ddc4cfdc865b4
