### ISSUE TITLE
Can't enable fcitx5-mozc on Chromium's file dialogue

### ISSUE THREAD

**Issue by utuhiro78** [fcitx/mozc#44]
## Description
Can't enable fcitx5-mozc on the latest Chromium's file dialogue.

## Steps to reproduce
Open https://github.com/fcitx/mozc by Chromium and press "Ctrl + S" (Save as).
I want to change the filename to "テスト.html".
Press "Ctrl + space" to enable fcitx5-mozc.
I couldn't enable fcitx5-mozc.

Fcitx5-mozc: https://github.com/fcitx/mozc/commit/4b2a3ece51a37e67bafa93bdfe7a64fee43163ee
Chromium: Version 117.0.5938.88 (Official Build) Arch Linux (64-bit)

I can enable fcitx5-mozc on this "Bug report".
I can enable fcitx5-mozc on the latest Firefox's file dialogue.

**Comment by wengxt** [comment]
why you report is to mozc? does it have anything to do with mozc?

most likely you didn't setup your environment variable like GTK_IM_MODULE to whole session, especially for dbus activation context.

Can you post the output of fcitx5-diagnose when the save dialog is opened?

**Comment by utuhiro78** [comment]
Hello wengxt,

> why you report is to mozc?

I found the problem when I had tried to enable fcitx5-mozc, so I reported it to here.

I wanted to know other users could enable fcitx5-mozc on Chromium's file dialog or not.

Sorry for annoying you.

**Comment by wengxt** [comment]
@utuhiro78  what I actually mean is that, this bug has no relationship to mozc. I bet if you use any other engine you will still have problem, which make it belongs to https://github.com/fcitx/fcitx5

**Comment by wengxt** [comment]
my question actually is that, is there anything special that makes you think this is directly related to mozc?
