### ISSUE TITLE
Build error: 

### ISSUE THREAD

**Issue by Brli** [fcitx/mozc#45]
## Description
A clear and concise description of what the issue is.

Bazel failed to analysis qt5 renderer

and the build process die out.

## Commit-id

e1cfe7d

## Build target

4. Others (no guarantee)

Archlinux PKGBUILD

## CI build status
Whether the current CI build status is `passing` or `failure`.
https://github.com/google/mozc#build-status

Choose either of them
1. passing
2. failure

passed.

## Environment
 - OS: Arch Linux
 - Python version (optional): 3.11.5-2
 - Qt5 version (optional): 5.15.10+kde+r158
 - Compiler version (optional): 

## Build commands
Steps of command lines to reproduce your error.
1. git ...
2. cd ...
3. bazel ...

## Error logs

```
Starting local Bazel server and connecting to it...
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
    currently loading: server ... (6 packages)
Analyzing: 6 targets (6 packages loaded, 0 targets configured)
Analyzing: 6 targets (49 packages loaded, 142 targets configured)
ERROR: Traceback (most recent call last):
	File "/build/.cache/bazel/_bazel_builduser/9b5f81099b6a0eb268b7c9c659566f23/external/qt_linux/BUILD.bazel", line 8, column 16, in <toplevel>
		hdrs = glob([
Error in glob: pattern cannot be absolute
ERROR: /build/mozc-ut/src/mozc/src/gui/tool/BUILD.bazel:94:18: no such target '@qt_linux//:qt_linux': target 'qt_linux' not declared in package '' defined by /build/.cache/bazel/_bazel_builduser/9b5f81099b6a0eb268b7c9c659566f23/external/qt_linux/BUILD.bazel (Tip: use `query "@qt_linux//:*"` to see all the targets in that package) and referenced by '//gui/tool:mozc_tool'
ERROR: Analysis of target '//gui/tool:mozc_tool' failed; build aborted: Analysis failed
INFO: Elapsed time: 9.060s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (51 packages loaded, 142 targets configured)
```

**Comment by wengxt** [comment]
I think it should be fixed by upstream? our CI is
