### ISSUE TITLE
kimpanel icon maybe fallback in a undesired way

### ISSUE THREAD

**Issue by wengxt** [fcitx/mozc#53]
fcitx-mozc-…. maybe wrongly fallback to fcitx.

This requires a similar fix like fcitx5-rime by renaming the icon.

**Comment by phoepsilonix** [comment]
I confirmed it on Manjaro and Ubuntu.
Icon is displayed in fcitx5-mozc.(8ff029c30)
Icon is not displayed in flatpak version of fcitx5-mozc(org.fcitx.Fcitx5.Addon.Mozc).

If the fcitx-mozc-data package is installed on Ubuntu, the icon will also appear in the flatpak version of fcitx5-mozc.
It seems better to change the icon installation destination for the flatpak version of fcitx5-mozc.
It will not be displayed if fcitx-mozc-data is not installed.

**Comment by wengxt** [comment]
@phoepsilonix there might be a bug after the icon renaming that I tends to resolve recently.

**Comment by wengxt** [comment]
@phoepsilonix  ah, I get it. The internal icon name transform ignores the new icon name fcitx_. I need to add support to that.

The reason is that flatpak doesn't allow export icon from addon. When the icon is exported, it must have the same icon name prefix as the app name.

So there's this piece of code 
https://github.com/fcitx/fcitx5/blob/cae526a0d98b82cbbc497f685afc784ab49403ca/src/lib/fcitx/icontheme.cpp#L800 to prepend the icon name, for all "fcitx" icon.

The reason that we move away from "fcitx-" to "fcitx_" is because "-" has special meaning in xdg icon spec. Which may make fcitx-mozc fallback to 'fctix', if your icon theme has only  "fcitx". Since breeze is bundling lots of fcitx icon, but not all, it leads to certain case that only the "fcitx" icon is shown in place.

Need to update the code there to fix the flatpak icon name mapping.

**Comment by phoepsilonix** [comment]
fcitx/fcitx5/pull/1050

**Comment by wengxt** [comment]
Rename is done at 
https://github.com/fcitx/mozc/commit/e13338a41329f58e724801771f0cecf7338e24fb

Close as the original issue is fixed.

**Comment by wengxt** [comment]
@phoepsilonix 
as for flatpak  fcitx5-unstable is updated, and flathub is being updated with cherry-pick 

https://github.com/flathub/org.fcitx.Fcitx5/commit/9537caeb179bd545eeec93bc9729627a08f755b9
