### ISSUE TITLE
Using dead keys in preedit

### ISSUE THREAD

**Issue by jansol** [fcitx/mozc#54]
### Summary

I am using a keyboard layout where ~ among other symbols are mapped to dead keys. I would like fcitx to pick up characters typed that way (e.g. dead key + space or dead key tapped twice) as part of the preedit string. Currently the characters get sent past fcitx, directly to the underlying application. The most common use for this would be converting ~ to 〜 which I do in this exact way on macOS, but haven't found a way to replicate it in fcitx yet. (I know I can type "nami" in mozc to get 〜 as a suggestion but the dead keys are much more convenient for me in this case)

**Comment by wengxt** [comment]
I can add composing support to mozc. At the same time, I'm just saying, maybe, you can set mozc to use a non-dead key layout if that works for you?

**Comment by wengxt** [comment]
@jansol add composing support from my point of view is like a per-engine effort, since the engine may prefer to handle the dead key directory with its own logic, dead key string won't be easily to integration into the engine logic (especially when engine maintains its own buffer that doesn't not accept random key/string).

**Comment by phoepsilonix** [comment]
# Before applying PR
## Layout
### English(us,alt. intl).
It will not be preedited, and only the dead key will be input.

### English(us,intl., with dead keys).
It will not be preedited, and only the dead key will be input.

### English(us,intl., with AltGr dead keys).
When inputting a dead key (+shift key), `(~) appears as a conversion candidate in preedit mode.

# When PR is applied
## Layout
### English(us,alt. intl).
When inputting a dead key (+shift key), `(~) appears as a conversion candidate in preedit mode.

### English(us,intl., with dead keys).
When inputting a dead key (+shift key), `(~) appears as a conversion candidate in preedit mode.

### English(us,intl., with AltGr dead keys).
When inputting a dead key (+shift key), `(~) appears as a conversion candidate in preedit mode.

**Comment by phoepsilonix** [comment]
# Before applying PR
## Layout
### English(us,alt. intl).
It will not be preedited, and only the dead key will be input.

### English(us,intl., with dead keys).
It will not be preedited, and only the dead key will be input.

### English(us,intl., with AltGr dead keys).
When tapping a dead key (+shift key), `(~) appears as a conversion candidate in preedit mode.

# When PR is applied
## Layout
### English(us,alt. intl).
When tapping the dead key (+shift key) twice, `(~) is displayed as a conversion candidate in preedit mode.

### English(us,intl., with dead keys).
When tapping the dead key (+shift key) twice, `(~) is displayed as a conversion candidate in preedit mode.

### English(us,intl., with AltGr dead keys).
When tapping a dead key (+shift key), `(~) appears as a conversion candidate in preedit mode.

**Comment by wengxt** [comment]
@phoepsilonix you probably think you’re pressing dead key while it’s not.

In dead altgr us layout, shift + “the key under esc”, is the normal ~. shift + altgr + that key is dead tilde.
